In [24]:
import numpy as np 
import pandas as pd

data=pd.DataFrame([[8,8,4],[7,7,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])
data


cgpa  profile_score  lpa
0     8              8    4
1     7              7    5
2     6             10    6
3     5             12    7

In [25]:
def initilize_parameters(layers_dim):
    np.random.seed(3)
    parameters={}
    l=len(layers_dim) 
    for i in range(1,l):
        parameters['w',str(i)]=np.ones(layers_dim[i-1],layers_dim[i])*.1
        parameters['b',str(i)]=np.zeros(layers_dim[i],1)
    return parameters

In [26]:
def sigmoid(z):
    A=1/1+np.exp(-z)
    return A

In [27]:
def linear_forward(A_prev,w,b):
    z=np.dot(w,T,A_prev)+b
    A=sigmoid(z)
    return z


In [28]:
def L_layers_forward(x,parameters):
    A=x
    l=len(parameters)
    for i in range(1,l+1):
        A_prev=A
        w1=parameters('w'+str(i))
        b1=parameters('b'+str(i))
        A=linear_forward(A_prev,w1,b1)
    return A ,A_prev

# ----Back propagation using keras-------

In [2]:
import numpy as np 
import pandas as pd

In [3]:
data=pd.DataFrame([[8,8,4],[7,7,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [4]:
data

cgpa  profile_score  lpa
0     8              8    4
1     7              7    5
2     6             10    6
3     5             12    7

In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [7]:
model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

c:\Users\Adeel\Desktop\Deep Learning\Deep_learning\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.get_weights()

[array([[-0.6074639 ,  0.27560043],
        [ 1.018108  ,  0.43542862]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.8193    ],
        [ 0.85211575]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
new_weights=[np.array([[.1,.1],[.1,.1]]
                      ,dtype=np.float32),
                      np.array([0.,0.],dtype=np.float32),
                      np.array([[.1],[.1]],dtype=np.float32),
                      np.array([0.],dtype=np.float32)
                      ]

In [13]:
model.set_weights(new_weights)

In [14]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [21]:
optmizers=keras.optimizers.Adam(learning_rate=.001)
model.compile(loss='mean_squared_error',optimizer=optmizers)

In [22]:
model.fit(data.iloc[:,0:-1].values,data['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 17.0862
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 20.4593
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 18.3789
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21.1804
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 17.6287 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 20.1837
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.4215
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 20.3075
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 14.3985
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 19.4361
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 17.8756
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 18.8088
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.7156
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 10.3360
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 11.2618
Epoch 16/75
4/4 ━━

In [23]:
model.get_weights()

[array([[0.38926548, 0.38926548],
        [0.38733763, 0.38733763]], dtype=float32),
 array([0.2927578, 0.2927578], dtype=float32),
 array([[0.39175102],
        [0.39175102]], dtype=float32),
 array([0.2518227], dtype=float32)]